### ISSUE TITLE
Is this a bug `Can't resolve '#apg-lite'` I am using swagger-ui-react

### ISSUE THREAD

**Issue by kivi** [swaggerexpert/openapi-path-templating#76] opened 2024-05-22 18:08 UTC
I am running a node.js App build on Next.js using Bun.

I think this the first time I am seeing an error, resolving dependencies with `#`

There are lot of error messages, but all say the same:

```js
Module not found: Can't resolve '#apg-lite'
> 1 | import { identifiers, utilities } from '#apg-lite';
```

**Comment by kivi** [comment] 2024-05-22 18:19
I have also tried with `pnpm`, so it does not have to do with `bun`

Removing `#` from the imports works.

I have just remove `#` in of `import {...} from '#apg-lite';  in node_modules/openapi-path-templating/*/files-that-error.mjs

And added `apg-lite` to my dependencies. 
That's my current workaround and it works.

**Comment by char0n** [comment] 2024-05-22 18:28
Hi @kivi,

It's because of this: https://github.com/char0n/openapi-path-templating/blob/main/package.json#L16. It's in import field support by Node.js since >=12.20.0. I'm not familiar with `Bun`, but Next.js@4 is supporting this natively.

**Comment by kivi** [comment] 2024-05-22 18:34
I saw that packages.json, that's why I was aksing if this a bug here or some other kind of incompatibility. But I am also not familiar with this kind of declaration in your packages.json and the import with `#`.
However I tried also with `pnpm` and it wasn't working either with same error message.



What else could I try to check if this a bug or not?

**Comment by char0n** [comment] 2024-05-22 18:39
@kivi  this is not a bug. This is just lack of support for standard features in your build chain. 
`pnpm`, `yarn` or `npm` has nothing to do with this. They will successfully install the package:

```sh
char0n@mortality-ntb:/tmp $ pnpm install openapi-path-templating
Packages: +2
++
Progress: resolved 2, reused 0, downloaded 2, added 2, done

dependencies:
+ openapi-path-templating 1.5.1

Done in 1.7s
```

**Comment by char0n** [comment] 2024-05-22 18:43
@kivi here is POC repository integrating Next@14 and swagger-ui-react: https://github.com/char0n/swagger-ui-nextjs

Builds without any issue.

**Comment by kivi** [comment] 2024-05-22 18:44
Your right, not a bug in this package.
I guess it's not my build chain. But some dependencies, that uses this package.

**Comment by char0n** [comment] 2024-05-22 18:52
> I guess it's not my build chain. But some dependencies, that uses this package.

What do you mean? Not sure if this was ironic or real message ;]

**Comment by char0n** [comment] 2024-05-22 18:57
@kivi Bun claim to support both `exports` and `imports` package.json fields. More info in: https://bun.sh/docs/runtime/modules

**Comment by kivi** [comment] 2024-05-22 18:57
@char0n Wheater your are right with my build chain. Or something else collides with this. I am not doing anything extraordinary, so wondering where the issue could be and everything else works, except accessing this package.
And since I was unfamiliar to the import with `#` and removing this was solving it.

No need here for ironic. The contrary, thanks for your replay and trying to help.

**Comment by char0n** [comment] 2024-05-22 19:14
@kivi ok understood.

Did some further investigation and managed to successfully install and run the package:

```sh
$ docker run --rm --init --ulimit memlock=-1:-1 -v $(pwd):/app -w /app oven/bun bun add node-gyp
$ docker run --rm --init --ulimit memlock=-1:-1 -v $(pwd):/app -w /app oven/bun bun add swagger-client
$ docker run --rm --init --ulimit memlock=-1:-1 -v $(pwd):/app -w /app oven/bun bun run test.js
```

**test.js**
```js
import SC from 'swagger-client';

console.dir(SC);
```

Result was:
```sh
[Function: Swagger]
```

---

Context: swagger-client depends on openapi-path-templating. swagger-client is then used in swagger-ui-react.

**Comment by char0n** [comment] 2024-05-22 19:15
Sorry I cannot help more.

**Comment by kivi** [comment] 2024-05-22 19:17
@char0n cheers! you did more than enough. 
Thanks. I will also dig deeper soon and will tell you about it.

**Comment by kivi** [comment] 2024-05-23 10:47
Maybe it's this error: https://github.com/oven-sh/bun/issues/10001

**Comment by char0n** [comment] 2024-05-23 11:18
@kivi thanks for the update

**Comment by rajatsandeepsen** [comment] 2024-06-04 00:53
# When running swagger-ui-react on nextjs
![image](https://github.com/char0n/openapi-path-templating/assets/93584596/a0e0476d-2048-42b4-95b0-0369b15dd488)

And this is your code
https://github.com/char0n/openapi-path-templating/blob/main/src/parse/callbacks/fragment-marker.js

![image](https://github.com/char0n/openapi-path-templating/assets/93584596/7be0739b-408d-4775-bc32-90b086173f08)

**Comment by char0n** [comment] 2024-06-04 05:50
@rajatsandeepsen here is POC running on Node.js >=16 and building latest swagger-ui-react https://github.com/char0n/swagger-ui-nextjs. I see no issues.

**Comment by rajatsandeepsen** [comment] 2024-06-04 11:27
Okay.. but why can't you use "apg-lite" as normal import?

I still don't understand the use of "#" 

It'll make easier for all of us 😊

**Comment by char0n** [comment] 2024-06-04 19:20
@rajatsandeepsen because "apg-lite" is [pure-esm](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and it would not work with swagger-client, which must work isomorphic-ally (running in Node.js >= 12.20.0 (ESM + CommonJS) and Browser).

If swagger-client (which swagger-ui-react uses) is used in CommonJS environment, it would just crash if we wouldn't be doing override with [imports field](https://nodejs.org/api/packages.html#subpath-imports).

I'll try to think of some compatible alternative, but all the modern tooling and very old Node.js supports `imports field` and it should just be an implementation detail for you (you shouldn't even be aware that it's there).

**Comment by noahhai** [comment] 2024-06-14 11:45
For anyone else dealing with this - I have a very similar setup as the example repo, but using typescript. I did not add the polyfill node --require ./ss-polyfills/File.js - still getting an issue.

I fixed by running:

```
pnpm patch  openapi-server-url-templating
pnpm patch openapi-path-templating
```

then making this change everywhere except in package.json for both packages, and committing the patch.

```
-var _apgLite = require("#apg-lite");
+var _apgLite = require("apg-lite");
```

**Comment by char0n** [comment] 2024-06-14 12:08
I'll release a new patch version without the `imports` field and I'll do the patching during the release process.

**Comment by char0n** [comment] 2024-06-14 19:37
Addressed in https://github.com/swaggerexpert/openapi-path-templating/pull/94

**Comment by char0n** [comment] 2024-06-14 19:42
Released as https://github.com/swaggerexpert/openapi-path-templating/releases/tag/v1.6.0

**Comment by char0n** [comment] 2024-06-14 19:42
Whenever swagger toolchain is now re-installed, the new version of openapi-path-templating will install and auto-resolve the issue.

**Closed by char0n** 2024-06-14 19:42 UTC

**Comment by char0n** [comment] 2024-06-14 19:58
`openapi-server-url-templating` addressed in https://github.com/swaggerexpert/openapi-server-url-templating/releases/tag/v1.1.0

**Comment by noahhai** [comment] 2024-06-14 20:17
Woah you are fast @char0n! Thank you so much :)
